---
- hosts: localhost
#  become: ture
  user: edureka

  tasks:
    - name: deploy SunnyPGPProject on kubernetes
      command: kubectl apply -f deployment.yaml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/pgpindustry-dep

