 
---
apiVersion: v1
kind: Service
metadata:
  name: pgpindustry-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pgpindustry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpindustry-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgpindustry 
  template:
    metadata:
      labels:
        app: pgpindustry
        version: pgpindustry-version-1
    spec:
      containers:
      - name: pgpindustry-version-1
        image: ssunnysingh/pgpedureka:sunnypgpproject
        env:
            - name: TZ
        imagePullPolicy: Always
        resources:
          requests: 
            memory: "512Mi"
            cpu: "0.25"
          limits: 
            memory: "768Mi"
            cpu: "0.5"
      terminationGracePeriodSeconds: 500
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pgpindustry-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgpindustry-dep  
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
